In [3]:
#i 0으로 초기화
i = 0
#i가 100보다 작을때까지 반복
while i < 100 : 
    #i에 1씩 더해준다.
    i += 1
    print(i, end = " ")

1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 100

In [10]:
#i 0으로 초기화
i = 0
#i가 100까지 범위를 준다음 숫자 한개씩 꺼내와서
#1씩 더해주고 출력
for i in range(100) :
    i += 1
    print(i, end = " ")

1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 100

In [11]:
#i 0으로 초기화
i = 0
#sum 0으로 초기화
sum = 0
#i가 100보다 작을때까지 반복
while i < 100 :
    #1씩 더해주고
    i += 1
    #sum에다가 누적한다
    sum = sum + i
print("sum = ",sum)

sum =  5050

In [12]:
i = 0
sum = 0
#i가 100보다 작을때까지 반복
while i < 100 : 
    #i에 1씩 더해준다
    i += 1
    #sum에 누적한다.
    sum = sum + i
print("sum = ",sum)

sum =  5050

In [14]:
i = 0
sum = 0
while i < 100 :
    #sum누적을 먼저 시켜서 마지막 값을
    #sum에 못담으니까 값이 더 작다.
    sum = sum + i
    i += 1
print("sum = ",sum)

sum =  4950

In [15]:
i = 0
sum = 0
#반복을 한번 더 돌았기때문에
#첫번째 값이랑 같게 나온다.
while i < 101 :
    sum = sum + i
    i += 1
print("sum = ",sum)

sum =  5050

In [19]:
#범위 1부터 9까지 1씩 증감해서 출력한다
for i in range(1,10,1) :
    print(i," ",end = " ")

1   2   3   4   5   6   7   8   9

In [25]:
#10까지 범위를 주고 반복
for i in range(10):
    print(i," ",end=" ")
print()
#1부터 9까지 반복
for i in range(1,10):
    print(i," ",end="")

0   1   2   3   4   5   6   7   8   9
1  2  3  4  5  6  7  8  9

In [27]:
#1부터 9까지 2씩 증가
for i in range(1,10,2):
    print(i," ",end="")
print()
#10부터 1까지 -1씩 증가
for i in range(10,0,-1):
    print(i," ",end="")

1  3  5  7  9
10  9  8  7  6  5  4  3  2  1

In [30]:
#10번 반복
for i in range(10):
    #i가 3이라면 탈출
    if(i==3):
        break
    print(i," ",end="")

0  1  2

In [32]:
#0부터 9까지 반복
for i in range(10):
    #i 가 3이라면
    if(i==3):
        #건너뛰기
        continue
    print(i," ",end="")

0  1  2  4  5  6  7  8  9

In [33]:
#i와 sum을 0으로 초기화
i=0;sum=0
while True:
    #i 1씩 누적
    i += 1
    #sum은 누적된 i를 누적
    sum += i
    #만약 i가 100이라면 탈출
    if(i==100): break
print("i=",i,"sum=",sum)

i= 100 sum= 5050

In [34]:
#1부터 120까지 반복
for i in range(1,121):
    #별을 출력하고 줄바꿈 안함
    print("*",end = "")
    #i가 30이되면 줄바꿈
    if(i%30==0) : 
        print(end="\n")

******************************
******************************
******************************
******************************

In [35]:
#첫번째 반복 1부터 9까지 반복
for i in range(1,10):
    #i가 1일때 j가 9번 반복
    for j in range(1,10):
        print( i,"*",j,"=",i*j)
    print("********************")

1 * 1 = 1
1 * 2 = 2
1 * 3 = 3
1 * 4 = 4
1 * 5 = 5
1 * 6 = 6
1 * 7 = 7
1 * 8 = 8
1 * 9 = 9
********************
2 * 1 = 2
2 * 2 = 4
2 * 3 = 6
2 * 4 = 8
2 * 5 = 10
2 * 6 = 12
2 * 7 = 14
2 * 8 = 16
2 * 9 = 18
********************
3 * 1 = 3
3 * 2 = 6
3 * 3 = 9
3 * 4 = 12
3 * 5 = 15
3 * 6 = 18
3 * 7 = 21
3 * 8 = 24
3 * 9 = 27
********************
4 * 1 = 4
4 * 2 = 8
4 * 3 = 12
4 * 4 = 16
4 * 5 = 20
4 * 6 = 24
4 * 7 = 28
4 * 8 = 32
4 * 9 = 36
********************
5 * 1 = 5
5 * 2 = 10
5 * 3 = 15
5 * 4 = 20
5 * 5 = 25
5 * 6 = 30
5 * 7 = 35
5 * 8 = 40
5 * 9 = 45
********************
6 * 1 = 6
6 * 2 = 12
6 * 3 = 18
6 * 4 = 24
6 * 5 = 30
6 * 6 = 36
6 * 7 = 42
6 * 8 = 48
6 * 9 = 54
********************
7 * 1 = 7
7 * 2 = 14
7 * 3 = 21
7 * 4 = 28
7 * 5 = 35
7 * 6 = 42
7 * 7 = 49
7 * 8 = 56
7 * 9 = 63
********************
8 * 1 = 8
8 * 2 = 16
8 * 3 = 24
8 * 4 = 32
8 * 5 = 40
8 * 6 = 48
8 * 7 = 56
8 * 8 = 64
8 * 9 = 72
********************
9 * 1 = 9
9 * 2 = 18
9 * 3 = 27
9 * 4 = 36
9 * 5 = 45
9 * 6 = 54
9 * 7 = 63
9 * 8 = 72
9 * 9 = 81
********************

In [36]:
#9번 반복한다.
for i in range(1,10):
    #9번 반복한다.
    for j in range(i,10):
        #
        print( "*",end="")
    print(end="\n")

*********
********
*******
******
*****
****
***
**
*

In [44]:
#i는 1로 초기화
i=1
#무한 반복
while True:
    #i를 j에 담는다
    j=i
    while True:
        #만약 j가 10이라면 탈출
        if(j == 10) : 
            break
        print( "*",end=  "")
        #j를 1씩 증감
        j+=1
    #i 가 10이 되면 탈출
    if(i == 10) : 
        break
    print(end = "\n")
    #i 1씩 증감
    i+=1

*********
********
*******
******
*****
****
***
**
*

In [45]:
#Mon 에 1저장
Mon=1
#각각 월의 마지막 날짜를 저장
for LastDay in [31,28,31,30,31,30,31,31,30,31,30,31]:
    print(Mon,"월 :",end="")
    #배열의 순서대로 가져와서 그 값만큼 반복돌려 출력
    for Day in range(1,LastDay+1):
        print(Day,end=",")
    print(end="\n")
    Mon+=1

1 월 :1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,
2 월 :1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,
3 월 :1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,
4 월 :1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,
5 월 :1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,
6 월 :1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,
7 월 :1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,
8 월 :1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,
9 월 :1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,
10 월 :1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,
11 월 :1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,
12 월 :1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,

In [46]:
#2부터 9까지 3씩 증감 반복
for i in range(2,10,3):
    #2부터 9까지 반복
    for j in range(2,10):
        print(i,"*",j,"=",i*j,end="\t")
        print(i+1,"*",j,"=",i*j,end="\t")
        #아래까지 출력하고 줄바꿈
        if(i+2!=10): 
            print(i+2,"*",j,"=",i*j,end="\n")
        else: print(end="\n")
    print(end="\n")

2 * 2 = 4	3 * 2 = 4	4 * 2 = 4
2 * 3 = 6	3 * 3 = 6	4 * 3 = 6
2 * 4 = 8	3 * 4 = 8	4 * 4 = 8
2 * 5 = 10	3 * 5 = 10	4 * 5 = 10
2 * 6 = 12	3 * 6 = 12	4 * 6 = 12
2 * 7 = 14	3 * 7 = 14	4 * 7 = 14
2 * 8 = 16	3 * 8 = 16	4 * 8 = 16
2 * 9 = 18	3 * 9 = 18	4 * 9 = 18

5 * 2 = 10	6 * 2 = 10	7 * 2 = 10
5 * 3 = 15	6 * 3 = 15	7 * 3 = 15
5 * 4 = 20	6 * 4 = 20	7 * 4 = 20
5 * 5 = 25	6 * 5 = 25	7 * 5 = 25
5 * 6 = 30	6 * 6 = 30	7 * 6 = 30
5 * 7 = 35	6 * 7 = 35	7 * 7 = 35
5 * 8 = 40	6 * 8 = 40	7 * 8 = 40
5 * 9 = 45	6 * 9 = 45	7 * 9 = 45

8 * 2 = 16	9 * 2 = 16
8 * 3 = 24	9 * 3 = 24
8 * 4 = 32	9 * 4 = 32
8 * 5 = 40	9 * 5 = 40
8 * 6 = 48	9 * 6 = 48
8 * 7 = 56	9 * 7 = 56
8 * 8 = 64	9 * 8 = 64
8 * 9 = 72	9 * 9 = 72

In [48]:
for i in range(2,10,3):
    for j in range(2,10):
        print(i,"*",j,"=",i*j,end="\t")
        print(i+1,"*",j,"=",(i+1)*j,end="\t")
        if(i+2!=10): 
            print(i+2,"*",j,"=",(i+2)*j,end="\n")
        else: print(end="\n")
    print(end="\n")

2 * 2 = 4	3 * 2 = 6	4 * 2 = 8
2 * 3 = 6	3 * 3 = 9	4 * 3 = 12
2 * 4 = 8	3 * 4 = 12	4 * 4 = 16
2 * 5 = 10	3 * 5 = 15	4 * 5 = 20
2 * 6 = 12	3 * 6 = 18	4 * 6 = 24
2 * 7 = 14	3 * 7 = 21	4 * 7 = 28
2 * 8 = 16	3 * 8 = 24	4 * 8 = 32
2 * 9 = 18	3 * 9 = 27	4 * 9 = 36

5 * 2 = 10	6 * 2 = 12	7 * 2 = 14
5 * 3 = 15	6 * 3 = 18	7 * 3 = 21
5 * 4 = 20	6 * 4 = 24	7 * 4 = 28
5 * 5 = 25	6 * 5 = 30	7 * 5 = 35
5 * 6 = 30	6 * 6 = 36	7 * 6 = 42
5 * 7 = 35	6 * 7 = 42	7 * 7 = 49
5 * 8 = 40	6 * 8 = 48	7 * 8 = 56
5 * 9 = 45	6 * 9 = 54	7 * 9 = 63

8 * 2 = 16	9 * 2 = 18
8 * 3 = 24	9 * 3 = 27
8 * 4 = 32	9 * 4 = 36
8 * 5 = 40	9 * 5 = 45
8 * 6 = 48	9 * 6 = 54
8 * 7 = 56	9 * 7 = 63
8 * 8 = 64	9 * 8 = 72
8 * 9 = 72	9 * 9 = 81

In [51]:
#i 가2부터 4까지 반복 총 3번 반복
for i in range(2,5):
    #j를 2부터 9까지 반복
    for j in range(2,10):
        #처음은 i곱하고 i+3을 하고 i+6을 곱해서 출력한다.
        print(i,"*",j,"=",i*j,end="\t")
        print(i+3,"*",j,"=",(i+3)*j,end="\t")
        #조건문에 10이되면 끝난다.
        if(i+6 != 10): print(i+6,"*",j,"=",(i+6)*j,end="\n")
        else: print(end="\n")
    print(end="\n")

2 * 2 = 4	5 * 2 = 10	8 * 2 = 16
2 * 3 = 6	5 * 3 = 15	8 * 3 = 24
2 * 4 = 8	5 * 4 = 20	8 * 4 = 32
2 * 5 = 10	5 * 5 = 25	8 * 5 = 40
2 * 6 = 12	5 * 6 = 30	8 * 6 = 48
2 * 7 = 14	5 * 7 = 35	8 * 7 = 56
2 * 8 = 16	5 * 8 = 40	8 * 8 = 64
2 * 9 = 18	5 * 9 = 45	8 * 9 = 72

3 * 2 = 6	6 * 2 = 12	9 * 2 = 18
3 * 3 = 9	6 * 3 = 18	9 * 3 = 27
3 * 4 = 12	6 * 4 = 24	9 * 4 = 36
3 * 5 = 15	6 * 5 = 30	9 * 5 = 45
3 * 6 = 18	6 * 6 = 36	9 * 6 = 54
3 * 7 = 21	6 * 7 = 42	9 * 7 = 63
3 * 8 = 24	6 * 8 = 48	9 * 8 = 72
3 * 9 = 27	6 * 9 = 54	9 * 9 = 81

4 * 2 = 8	7 * 2 = 14
4 * 3 = 12	7 * 3 = 21
4 * 4 = 16	7 * 4 = 28
4 * 5 = 20	7 * 5 = 35
4 * 6 = 24	7 * 6 = 42
4 * 7 = 28	7 * 7 = 49
4 * 8 = 32	7 * 8 = 56
4 * 9 = 36	7 * 9 = 63